### ISSUE TITLE
[BUG] Unable to install Klipper Screen - Error building numpy wheels

### ISSUE THREAD

**Issue by cottec** [Guilouz/Klipper-Flsun-Speeder-Pad#13]
during installation of Klipper Screen ./scripts/KlipperScreen-install.sh
it's stopping with an error:

Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... error
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
Error: pip install exited with status code 0
Unable to install dependencies, aborting install.

did anyone already experience that and can support?

full log file:
[numpy4.txt](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/files/9940386/numpy4.txt)

**Comment by Guilouz** [comment]
Already reported, it's not related to my KlipperScreen version, same issue with official build.
