### ISSUE TITLE
timelapse indique DETACHED

### ISSUE THREAD

**Issue by gigis57** [Guilouz/Klipper-Flsun-Speeder-Pad#17]
Bonjour,

J'ai installé par 2x la pad (3 instances) et quand j'arrive à l'installation TIMELAPSE, j'ai sur mainsail -> timelapse indique DETACHED et même le rafraichissement ne fonctionne pas et ni soft ni hard recovery.

Qu'est-il possible de faire ? Merci

![mS95sWf](https://user-images.githubusercontent.com/11633097/201231716-08398995-559b-4849-bb42-b08181010ad0.png)

**Comment by Guilouz** [comment]
Est-ce que tu as redémarré entre temps ?

**Comment by gigis57** [comment]
oui j'ai redemarré entre chaque étape demandé. et comme dis plus je fais et refais l'installation 2x de suite car la 1ière je pensais avoir oublié un truc mais j'ai copié/collé 1 à 1 les étapes décrites. (3 instances)

**Comment by gigis57** [comment]
Bien apparemment, je l'ai résolu en supprimant manuellement le dossier timelapse et en le réinstallant. Je poursuis les étapes suivantes. Merci
