### ISSUE TITLE
Klipper not loading after Enable Root Access 

### ISSUE THREAD

**Issue by ArikMerzon1** [Guilouz/Klipper-Flsun-Speeder-Pad#20]
I've followed all the steps of the `Enable Root Access` guide twice with the same outcome.

```
Klipper has encountered an error.
Issue a FIRMWARE RESTART to attempt fixing the issue.

mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE RESTART" command to reset the firmware, reload the config, and restart the host software.

```
![IMG_3521](https://user-images.githubusercontent.com/36950177/202704916-c6eb6e65-b337-4d70-9fe7-43c1a8a37a53.jpg)

**Comment by Guilouz** [comment]
You must not have followed all the steps because I see that you still have the version of KlipperScreen from Flsun.
