### ISSUE TITLE
Extruder doesn't work

### ISSUE THREAD

**Issue by ArikMerzon1** [Guilouz/Klipper-Flsun-Speeder-Pad#21]
I've followed through with the tutorial and everything seems to be fine.
I did all the calibrations.
Started a new print and although the print head is moving the extruder doesn't work.
I've tried to extrude manually and it's the same thing no extrusion and no errors in the console.
I checked the cables and they are fine.

I can provide more data 

*as a side note, the extruder was working

**Comment by Guilouz** [comment]
which printer?

**Comment by ArikMerzon1** [comment]
Speed Racer with a Nano V3 board

**Comment by Guilouz** [comment]
Do you use the correct printer.cfg file for it?

**Comment by ArikMerzon1** [comment]
I've uploaded the `printer.cfg` with the rest of the Configurations files
But now I see that I have multiple printer-####_####.cfg files
Is it correct?

![Screenshot 2022-11-22 at 12 54 28](https://user-images.githubusercontent.com/36950177/203307847-1c723a31-f876-4dad-b97f-24b4a1bfdb5b.png)

**Comment by Guilouz** [comment]
Stock folder?

Yes it’s normal it’s backup files.

**Comment by ArikMerzon1** [comment]
you mean this `/Klipper-Flsun-Speeder-Pad-main/Configurations/FLSUN Super Racer/Robin Nano 3.0-3.1 - LGX Lite`

**Comment by Guilouz** [comment]
Do you have LGX Lite extruder ?

**Comment by ArikMerzon1** [comment]
sorry, my bad it's stock extruder 
this is my `printer.cfg`
`#   _____             __ _                       _   _                
#  / ____|           / _(_)                     | | (_)                
# | |     ___  _ __ | |_ _  __ _ _   _ _ __ __ _| |_ _  ___  _ __  ___ 
# | |    / _ \| '_ \|  _| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \/ __|
# | |___| (_) | | | | | | | (_| | |_| | | | (_| | |_| | (_) | | | \__ \
#  \_____\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|___/
#                           __/ |                                      
#                          |___/    
#
# Klipper Configurations - Flsun Super Racer      
#
# Guislain Cyril

# MKS Robin Nano V3.0/V3.1
# When running "make menuconfig"
#
# [*] Enable extra low-level configuration options
#     Micro-controller Architecture (STMicroelectronics STM32)  --->
#     Processor model (STM32F407)  --->
#     Bootloader offset (48KiB bootloader (MKS Robin Nano V3))  --->
#     Clock Reference (8 MHz crystal)  --->
#     Communication interface (USB (on PA11/PA12))  --->
# (250000) Baud rate for serial port
# ()  GPIO pins to set at micro-controller startup (NEW)
#
# Note that the "make flash" command does not work with this board.
# Rename the file out/klipper.bin to Robin_nano_v3.bin, copy it an microSD 
# card, insert it in the printer and restart it.


########################################
# Editable Settings
########################################

# Notes: Some settings can be enabled or disabled by removing or adding the '#' symbol
#
# PID (pid_Kp, pid_Ki, pid_Kd) --> [extruder] and [heater_bed] sections
# E-Steps Extruder (rotation_distance) --> [extruder] section --> full_steps_per_rotation * microsteps / steps_per_mm = rotation_distance
# Pressure Advance (pressure_advance) --> [extruder] section -- See: https://www.klipper3d.org/Pressure_Advance.html
# Firmware Retraction --> [firmware_retraction] section -- Requires "Klipper Settings Plugin" for Cura -- See: https://github.com/jjgraphix/KlipperSettingsPlugin
# ADXL345 function for resonance testing --> Enable/Disable [include adxl345_pico.cfg] or [include adxl345_fysetc.cfg] -- Configuration in [input_shaper] section -- See: https://www.klipper3d.org/Measuring_Resonances.html
# NeoPixels function --> Enable/Disable [include neopixels.cfg]
# Timelapse function --> Enable/Disable [include timelapse.cfg]


########################################
# Included Files
########################################

[include macros.cfg]
#[include adxl345_pico.cfg]  #Enable if you want to use ADXL with Rapsberry Pi Pico
#[include adxl345_fysetc.cfg]  #Enable if you want to use ADXL with Fysetc Portable Input Shaper
#[include timelapse.cfg]  #Enable if you want to use Timelapse
#[include neopixels.cfg]  #Enable if you want to use Neopixels


########################################
# Printer Settings
########################################

[printer]
kinematics: delta
max_velocity: 300
max_accel: 4000
max_accel_to_decel: 2000
square_corner_velocity: 5
max_z_velocity: 300
print_radius: 132
minimum_z_position= -5
#delta_radius: 151.7


########################################
# X Stepper Motor & Driver Settings
########################################

[stepper_a]
step_pin: PE3
dir_pin: PE2
enable_pin: !PE4
microsteps: 16
rotation_distance: 40
endstop_pin: PA15
homing_speed: 50
homing_retract_dist: 5.0
homing_retract_speed: 10
#angle: 210
#position_endstop: 336
#arm_length = 315

[tmc2209 stepper_a]
uart_pin: PD5
run_current: 1.138
hold_current: 0.5
stealthchop_threshold: 999999


########################################
# Y Stepper Motor & Driver Settings
########################################

[stepper_b]
step_pin: PE0
dir_pin: PB9
enable_pin: !PE1
microsteps: 16
rotation_distance: 40
endstop_pin: PD2
#angle: 330

[tmc2209 stepper_b]
uart_pin: PD7
run_current: 1.138
hold_current: 0.5
stealthchop_threshold: 999999


########################################
# Z Stepper Motor & Driver Settings
########################################

[stepper_c]
step_pin: PB5
dir_pin: PB4
enable_pin: !PB8
microsteps: 16
rotation_distance: 40
endstop_pin: PC4
#angle: 90

[tmc2209 stepper_c]
uart_pin: PD4
run_current: 1.138
hold_current: 0.5
stealthchop_threshold: 999999


########################################
# Extruder & Driver Settings
########################################

[extruder]
step_pin: PD6
dir_pin: !PD3
enable_pin: !PB3
microsteps: 16
rotation_distance: 7.805
nozzle_diameter: 0.4
filament_diameter: 1.750
heater_pin: PE5
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC1
min_temp: -5
max_temp: 275
max_extrude_cross_section: 110 
max_extrude_only_distance: 1100
#pressure_advance: 0.04
#pressure_advance_smooth_time: 0.01
control = pid
pid_kp = 18.240
pid_ki = 0.558
pid_kd = 149.109

[tmc2209 extruder]
uart_pin: PD9
run_current: 1.1
hold_current: 0.5
stealthchop_threshold: 999999


########################################
# Bed Settings
########################################

[heater_bed]
heater_pin: PA0
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC0
min_temp: -5
max_temp: 115
control = pid
pid_kp = 71.041
pid_ki = 1.422
pid_kd = 887.123


########################################
# Filament Sensor Settings
########################################

[filament_switch_sensor filament_sensor]
pause_on_runout: True
runout_gcode: M600
switch_pin: PA4


########################################
# Fans Settings
########################################

[fan]
pin: PC14

[heater_fan Hotend]
pin: PB0
heater_temp: 50.0


########################################
# Probe Settings
########################################

[probe]
pin: !PC8
x_offset: 0
y_offset: 0
#z_offset: 16.85
speed: 10
samples: 3
samples_result: average
sample_retract_dist: 3
samples_tolerance: 0.02
samples_tolerance_retries: 5


########################################
# Delta Calibration & Mesh Settings
########################################

[delta_calibrate]
radius: 130
horizontal_move_z: 25
Speed: 100

[bed_mesh]
speed: 80
horizontal_move_z: 25
mesh_radius: 130
mesh_origin: 0,0
mesh_pps: 5,5
round_probe_count: 5
algorithm: bicubic
bicubic_tension: 0.1
move_check_distance: 3
#fade_start: 1
#fade_end: 30


########################################
# Temperature Controls
########################################

[verify_heater extruder]
max_error: 500
hysteresis: 20

[verify_heater heater_bed]
max_error: 120
hysteresis: 5


########################################
# Firmware Retraction Settings
########################################

[firmware_retraction]
retract_length: 1.2
retract_speed: 35
unretract_extra_length: 0.05
unretract_speed: 35


########################################
# Input Shaper Settings
########################################

[input_shaper]
shaper_freq_x: 25.00
shaper_type_x = mzv
shaper_freq_y: 23.29
shaper_type_y = mzv


########################################
# G-Code Macros & Events
########################################

[idle_timeout]
timeout: 1800

[save_variables]
filename: ~/printer_data/config/variables.cfg

[gcode_arcs]

[pause_resume]

[display_status]

[respond]

[exclude_object]

[virtual_sdcard]
path: ~/printer_data/gcodes

[endstop_phase stepper_a]
endstop_align_zero: false

[endstop_phase stepper_b]
endstop_align_zero: false

[endstop_phase stepper_c]
endstop_align_zero: false 


########################################
# MCU Settings
########################################

[mcu]
serial: /dev/serial/by-id/usb-Klipper_stm32f407xx_3A004F000D50414238323520-if00
restart_method: command

[temperature_sensor Speeder_Pad]
sensor_type: temperature_host
min_temp: 10
max_temp: 100

[temperature_sensor Motherboard]
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100


########################################
# LED Settings
########################################

[neopixel RGB]
pin: PB2
chain_count: 34
color_order: GRB
initial_RED: 0.0
initial_GREEN: 0.0
initial_BLUE: 0.0

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	-1.862008, -1.862008, -1.862008, -1.862008, -1.862008
#*# 	-2.241428, -2.241428, -1.937405, -1.770595, -1.770595
#*# 	-2.149645, -2.005184, -1.704167, -1.492684, -1.362145
#*# 	-1.551624, -1.551624, -1.264554, -1.043291, -1.043291
#*# 	-0.873923, -0.873923, -0.873923, -0.873923, -0.873923
#*# tension = 0.1
#*# min_x = -130.01
#*# algo = bicubic
#*# y_count = 5
#*# mesh_y_pps = 5
#*# min_y = -130.0
#*# x_count = 5
#*# max_y = 130.0
#*# mesh_x_pps = 5
#*# max_x = 130.01
#*#
#*# [printer]
#*# delta_radius = 151.918026
#*#
#*# [stepper_a]
#*# angle = 210.297779
#*# arm_length = 315.000000
#*# position_endstop = 338.526098
#*#
#*# [stepper_b]
#*# angle = 329.977355
#*# arm_length = 315.000000
#*# position_endstop = 337.745403
#*#
#*# [stepper_c]
#*# angle = 90.000000
#*# arm_length = 315.000000
#*# position_endstop = 336.783223
#*#
#*# [delta_calibrate]
#*# height0 = 16.85
#*# height0_pos = 25668.333,25668.333,25668.333
#*# height1 = 16.85
#*# height1_pos = 31248.333,31248.333,22588.333
#*# height2 = 16.85
#*# height2_pos = 25087.000,34601.000,25087.000
#*# height3 = 16.85
#*# height3_pos = 22820.333,30416.333,30416.333
#*# height4 = 16.85
#*# height4_pos = 24903.333,24903.333,31711.000
#*# height5 = 16.85
#*# height5_pos = 29525.667,22929.333,29525.667
#*# height6 = 16.85
#*# height6_pos = 32986.667,24910.667,24910.667
#*#
#*# [probe]
#*# z_offset = 15.550
#*#
#*# [endstop_phase stepper_a]
#*# trigger_phase = 45/64
#*#
#*# [endstop_phase stepper_b]
#*# trigger_phase = 55/64
#*#
#*# [endstop_phase stepper_c]
#*# trigger_phase = 60/64
`

**Comment by ArikMerzon1** [comment]
and i did use the right folder `/Klipper-Flsun-Speeder-Pad-main/Configurations/FLSUN Super Racer/Robin Nano 3.0-3.1 - Stock`

**Comment by ArikMerzon1** [comment]
Redid all the steps once again and it's working.
Probably I've missed something along the way.

@Guilouz One question though, is there a way (config) to turn off the small screen of the SR?

**Comment by Guilouz** [comment]
Just disconnect it
