### ISSUE TITLE
Yeah, it's me again...

### ISSUE THREAD

**Issue by Liight07** [Guilouz/Klipper-Flsun-Speeder-Pad#23]
Hello, it's me again... 

I'm sorry to be such a trash newbie with all 3D Stuff but after 2 days of searching, testing and destroying my SR leveling switch, I can't stay without a solution. 
Since the update, I can't make a simple Z Calibration. The "Probe" one just go down and finally crashed and broke my leveling sensor... I did the Restoration to the standard Klipper firmware on my SpeedPad, but I have the same results
Think I tried everything I could with my knowledge and some tutorials on Youtube and Klipper Documentation [https://www.klipper3d.org/Probe_Calibrate.html]. The macro SET GCODE OFFSET don't do anything unless the error message "Unable to save variable"

So if someone care about me and my issue I'll be glad... 😄 

I tried to figure out what I did wrong but I haven't any idea. Thanks your time, support and kindness 
[moonraker-1.log](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/files/10126571/moonraker-1.log)
[klippy-1 (1).log](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/files/10126572/klippy-1.1.log)

**Comment by Guilouz** [comment]
No support for this kind of issue of Klipper here. Use Issues tab only to report issue for the content of this git.
