### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by lloydpick** [Guilouz/Klipper-Flsun-Speeder-Pad#28]
It would be really useful to get a changelog file on the repository, that way its very easy to know whats been adjusted without having to go through the commits one by one. eg.

2022-12-12
* Adjusted START_PRINT macro for latest Klipper (G3 Changes)

etc

**Comment by Guilouz** [comment]
I have planned to do that.

**Comment by Guilouz** [comment]
It's done : https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad#repo-changelog
