### ISSUE TITLE
Problème connexion wifi

### ISSUE THREAD

**Issue by Flazor-sun** [Guilouz/Klipper-Flsun-Speeder-Pad#32]
Bonjour, 

Je me permets de vous contacter car j'ai fait la mise à niveau de mon imprimante V400. Tout c'est bien passé.
Sauf que j'ai voulu la changer de wifi (après m-à-j) est la, impossible de la connecter au réseau voulu, j'ai le message Attempting to connect to (SSID).
J'ai donc supprimer le réseau sur lequel je voulais la connecter en laissant l'ancien, puis redémarré. Elle ne se reconnecte même pas à l'ancien. 
Alors j'ai essayé de supprimer l'ancien et reconnecté, toujours pareil j'ai le même défaut qu'expliqué ci-dessus (attempting).
Cela serait-il dû modification de l'emplacement wifi?

Merci d'avance

![klipperScreen_fault](https://user-images.githubusercontent.com/121314487/209395538-a752b166-7998-4c34-a4dc-11f40d8172f7.jpg)

**Comment by Guilouz** [comment]
Problème non lié au github. Pour la prochaine fois merci de ne reporter que les problème lié au contenu du github.

La partie wifi de l'OS du pad est vraiment merdique. Quelqu'un qui a changé de box a eu le même tour, il a dû réinstaller le pad.

**Comment by Flazor-sun** [comment]
Très bien c'est noté, merci de la rapidité.
Bonnes fêtes ;)
