### ISSUE TITLE
SD card formating

### ISSUE THREAD

**Issue by phnxdrgn536** [Guilouz/Klipper-Flsun-Speeder-Pad#36]
in the guide you should put a warning at the top to make sure your SD card is not only formatted in FAT32, but that the partition is a PRIMARY partition and not a data partition... any time i used windows quick format to format the card to FAT32 it would format the partition as a data partition and i spent hours worried i bricked my printer cause the motherboard wouldn't install the new firmware off the SD card

**Comment by flasher69** [comment]
True! I had the same issue. I used another SD-card and that worked. How do you format a SD-card with only Primary anyway?
