### ISSUE TITLE
Neopixel in MKS Robin Nano v2.0 for Flsun v400

### ISSUE THREAD

**Issue by Kortivex** [Guilouz/Klipper-Flsun-Speeder-Pad#39]
Hello @Guilouz, I have all the materials and I have made a direct connection to the port that appears in the instructions for that board as well as adding the settings and the menu as indicated but they do not turn on, do you know what it could be or details that I have overlooked? ?

**Comment by Guilouz** [comment]
No user support here. Thanks.
