### ISSUE TITLE
Speeder pad Moonraker issue

### ISSUE THREAD

**Issue by abhishekgyani** [Guilouz/Klipper-Flsun-Speeder-Pad#41]
Hi,I tried restarting the firmware and i was able to print a model and then afterwards im unable to connect to printer and its showing moonraker connection issue, moonraker might have been wrongly parsed error. the printer is showing disconnecting. can you help me out?
![image](https://user-images.githubusercontent.com/55229787/212586683-22c1dc66-67d6-48f7-8778-14a6c309adb9.png)
![image](https://user-images.githubusercontent.com/55229787/212586782-57e57144-fabf-4c23-a950-ab36a7eb580e.png)

**Comment by Guilouz** [comment]
No user support here. Thanks.
