### ISSUE TITLE
Tailscale gets reinstalled bricking wifi

### ISSUE THREAD

**Issue by andrewcharnley** [Guilouz/Klipper-Flsun-Speeder-Pad#42]
Unsure how it happened but at some point after enabling the klipperscreen auto update this package was reinstalled. Wifi won't connect now.

Add a rule to apt to block the package.

sudo apt-mark hold tailscale

**Comment by Guilouz** [comment]
No issue for me I can update tailscale without issue.

**Comment by andrewcharnley** [comment]
Problem solved then, your guide says to remove it then it gets automatically installed later on and bricks the wifi. No issue.
