### ISSUE TITLE
SHH password denied

### ISSUE THREAD

**Issue by elladd2007** [Guilouz/Klipper-Flsun-Speeder-Pad#48]
Hi ,
Try to ssh to speed ped but no seccses.

username: pi
password: flsun , v400 , flsun-v400 (every time diff password)

I try by using the git instruction -> no seccses.
Try by PUTTY -> No seccses.

The speed ped write the name Flsun-V400 at top

**Comment by Warren73** [comment]
If you can't get in with the pi / flsun password then odds are you didn't do the recovery image right. Maybe revisit the first part of the instructions about restoring OS image file. Once you do that I never have a problem getting in with those default creds, that's what's built into the image you should be installing.
