### ISSUE TITLE
Wifi breaking

### ISSUE THREAD

**Issue by Warren73** [Guilouz/Klipper-Flsun-Speeder-Pad#49]
So I've had this happen twice now. I've gone through the process and rooted and everything seems to be functioning normal but then wifi breaks and gets set to eth0. It still shows the wifi connections and even says it's connected, but it will not work over wifi nor does it actually get an ip address so I can't ssh into it. I believe it happens when I used the emergency stop red button on the speeder pad but can't say for sure as I haven't tested it out repeatedly.

Not sure if there's a fix since there's no network access and I can't ssh into it nor is there a command line I can access from the pad itself. The only console on there does macros only from what I can tell. 

I'm going to reload it again this morning and I might try to recreate this just to verify. But it's happened twice now and I'm strongly considering ditching this lame ass speeder pad and just installing something else to be the controller.

**Comment by Warren73** [comment]
Just a follow up, reinstalled from the image and went through the process again. At about three different times in the process I did an emergency stop but it did not switch to eth0 again. Such a weird error, really wish I could solder better so I could put an actual ethernet port on this thing.

**Comment by phnxdrgn536** [comment]
Do you think a USB to ethernet adapter would work? Wonder if the speeder
pad would recognize it…

**Comment by Guilouz** [comment]
Please don't use pull request for support.It's only to report an issue on github.
