### ISSUE TITLE
Utiliser gcode sur clef USB

### ISSUE THREAD

**Issue by ManuMod** [Guilouz/Klipper-Flsun-Speeder-Pad#5]
Même si l'envoi direct du gcode sur Mainsail est l'utilisation principale, je souhaiterai pouvoir conserver la fonctionnalité de lecture des gcodes sur clef USB.

Le montage de la clef USB n'est pas automatique et une fois montée en SSH, elle n'est pas reconnue dans Mainsaill.

Faut-il mettre en place qq chose du style autofs ou script, associé à un symlink sur 1 dossier dédié dans pi/gcodes_files ?

**Comment by Guilouz** [comment]
C’est pas le but de Klipper de print via clé USB ou microSD. C’est bien pour cette raison que ce n’est pas une fonctionnalité de Mainsail.
Il me semble que l’USB est monté uniquement au démarrage si une clé usb est insérée.
Je t’avouerais que je n’ai pas testé, j’envoie tous mes gcode depuis Cura directement sur le pad et ensuite je lance l’impression depuis le pad.

**Comment by ManuMod** [comment]
Dsl, effectivement la clef est correctement montée au démarrage et même à chaud, mais dans /pi/gcode_files/USB-Disk alors que Mainsaill utilise /printer_data/gcodes.

**Comment by Guilouz** [comment]
Merci de l'info, je vais rajouté ça au tuto.

**Comment by ManuMod** [comment]
Je pense qu'il serait plus propre de faire un symlink sur les dossiers gcode uniquement et cela permettrai pour le mode 3 instances (que je compte toujours essayer) de faire un symlink par printer_data sur le même dossier gcodes. Plus simple si une seule et même base de gcode, non?

**Comment by Guilouz** [comment]
Oui ça peut être réalisable avec:

ln -s /home/pi/gcode_files/USB-Disk /home/pi/printer_data_1/gcodes/USB-Disk
ln -s /home/pi/gcode_files/USB-Disk /home/pi/printer_data_2/gcodes/USB-Disk
ln -s /home/pi/gcode_files/USB-Disk /home/pi/printer_data_3/gcodes/USB-Disk

J'ai pas encore vraiment poussé les recherches avec plusieurs instances.

**Comment by ManuMod** [comment]
Effectivement ce serait LA méthode pour 3 instances.

Ce que j'évoquais était plutôt de limiter le symlink au /home/pi/gcode_files/, mais après mûre réflexion (ou plutôt 1 peu de repos ;-), c'est une bêtise pour les 3 instances, au vue des config dédiées aux imprimantes et/ou PLA.

**Comment by Guilouz** [comment]
Oui car chaque imprimante est différente et n’utilisent pas forcément toutes les mêmes gcodes.
Il est préférable d’avoir pour chacunes d’elles leurs dossiers gcode.
