### ISSUE TITLE
Shutdown via webinterface triggers a reboot

### ISSUE THREAD

**Issue by FunnyJoker87** [Guilouz/Klipper-Flsun-Speeder-Pad#52]
Hi, do you now about the issue that the speeder pad can't shutdown via the webinterface or a ssh session? If i do this the speeder pan instantly reboots. But if i do a shutdown on the touch screen of the speeder pan it's shutting down normal.

**Comment by Guilouz** [comment]
It should be fixed by last Moonraker commit.

See : https://github.com/Arksine/moonraker/issues/546

**Comment by FunnyJoker87** [comment]
Ahh ok so it's a bug in moonraker! I understand
Thank you for all your hours of work!
