### ISSUE TITLE
Unable to recovery klipper

### ISSUE THREAD

**Issue by itajackass** [Guilouz/Klipper-Flsun-Speeder-Pad#56]
![IMG20230123183645](https://user-images.githubusercontent.com/17260726/214110953-255cb308-35f0-42e6-b7ea-3f52321abf1c.jpg)

Today, Every time i poweron speeder pad i get INVALID klipper message. I tried hard and soft recovery without success... It work about 10 minutes on this screen (see pic), then fail.

**Comment by itajackass** [comment]
after some retry i get klipper valid again. before this problem I've assigned fixed IP of speederpad into my network to 192.168.1.102........now when i power on speederpad I see into my network 2 different devices with same name SPEEDERPAD and 2 different MAC ADDRESS and of course 2 different IP.....192.168.1.102 (fixed ip...but not reachable)....and 192.168.1.106 (dhcp....working)......Why?

**Comment by Guilouz** [comment]
No support here. Please only post issues related to github.
